baseURL = "http://zteo.com/"
languageCode = "en-us"
title = "The Nexus"
theme = "bleak"

pygmentsUseClasses = true
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = false

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[params]
  subtitle = "Chris' Den Of Confusion"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 1
